### ISSUE TITLE
FYI: new basecaller Flappie available

### ISSUE THREAD

**Issue by alanlorenzetti** [rrwick/Basecalling-comparison#14]
Hi Ryan. Thank you for this nice basecaller comparison.

I attended to NCM last month and learned ONT came up with a new basecaller called Flappie (https://github.com/nanoporetech/flappie). You can see more about it on Clive's talk at NCM (16:35; https://nanoporetech.com/about-us/news/clive-g-brown-nanopore-community-meeting-2018-talk).

According to him, "Albacore is no more" (23:15). We should to stick to Guppy and Flappie.
It would be great to have Flappie incorporated to this comparison.

cheers,
Alan.

**Comment by ExplodingCabbage** [comment]
Flappie is included as of https://github.com/rrwick/Basecalling-comparison/commit/4a44836524f5ca6bdaf150ae240e9796eb8d84c9; this issue should be closed.

**Comment by alanlorenzetti** [comment]
Thank you!
