### ISSUE TITLE
Connection refused for reference assembly

### ISSUE THREAD

**Issue by cjw85** [rrwick/Basecalling-comparison#2]
The link to the reference assembly does not appear to be public (though the raw fast5s are).

**Comment by rrwick** [comment]
That file should have been public, but this [isn't the first time](https://github.com/rrwick/Unicycler/issues/35) somebody has let me know about figshare downloading issues.

I've changed the links [in the README](https://github.com/rrwick/Basecalling-comparison#data-availability) so they no longer directly point to the download. Now they link to the figshare page, and you'll need to start the download from there. I hope that helps - let me know!

**Comment by cjw85** [comment]
Thanks.
