### ISSUE TITLE
Demultiplexed fast5s?

### ISSUE THREAD

**Issue by nataliering** [rrwick/Basecalling-comparison#3]
Hi Ryan

Great comparison, thanks for sharing it! One question, and I'm probably being stupid:

How did you collect the fast5 reads for each barcode to use with Nanopolish? Can Porechop (or Albacore) demultiplex the reads whilst they're still fast5s? Or did you demultiplex the fastqs and then use the read names to extract the reads from the fast5 files? Until now I'd been thinking I wouldn't be able to use Nanopolish on my barcoded runs, so am pleased there is a way to do it, even if your results showed it doesn't make massive improvements to the assemblies...!

Thanks,
Nat

**Comment by rrwick** [comment]
I did the second thing you said: use the read names from a demultiplexed fastq to gather up the relevant fast5s. It worked but was a bit clumsy.

That being said, I suspect it's no longer necessary with the recent Nanopolish improvements. I think that if you ran `nanopolish index` on your demultiplexed fastq and pointed it to the directory of _all_ fast5s, it should work fine. One thing to keep in mind though: `nanopolish index` does seem to be picky about [how the reads are named](https://github.com/jts/nanopolish/issues/223#event-1251108817).
