### ISSUE TITLE
Combine with genechips?

### ISSUE THREAD

**Issue by Nanoize** [rrwick/Basecalling-comparison#6]
Great article!

I had not been aware how close nanopores were to a widespread commercial launch.

Would you have a reference for a timeseries on error rates of nanopores? I would love to know when we could expect nanopores to rollout to scale.

Regarding the systematic nature of the errors, would such errors occur at predictable places in everyone's genomes? If it were possible to reduce nanopore errors to 1 million and the same errors were mostly shared by everyone, then combining a $50 gene chip with nanopore technology would give a human genome with only 
thousands of errors; would even be less when the entire set of human SNPs are found.

**Comment by rrwick** [comment]
I'd say that ONT isn't just close to a widespread commercial launch - they are there!

I don't have a longer range time series on ONT error rates, but looking at the Albacore error rates [here](https://github.com/rrwick/Basecalling-comparison#read-identity) shows how far they've come in the last year. Version 0.8.4 (the first Albacore version in my comparison) was released in February 2017.

Your question about the predictability of the assembly errors is a good one, but I don't have an answer. While a gene chip might work, a more common approach is to use both Nanopore and Illumina sequencing together. The Nanopore read lengths allow for a contiguous assembly, and the Illumina reads can correct most of the errors. This approach works very well for non-repetitive parts of the genome.  I also suspect that someone could correct most of the errors by comparing to known haplotypes, but I'm not sure (I work mostly in bacterial genomics, not human genomics).

Ryan
