### ISSUE TITLE
question about Nanopolish fasta extraction

### ISSUE THREAD

**Issue by ma-diroma** [rrwick/Basecalling-comparison#8]
Hi, 

you said 

> Since v0.8, Nanopolish can be run without event-data-containing fast5 files, which lets it work with any basecaller

however I am using Nanopolish 0.9.0 and `nanopolish extract` ends with this error

`no basecalling data suitable for nanoplish`

I checked my fast5 files and the dataset `/Analyses/Basecall_1D_000/BaseCalled_template/Events` is missing while I see the `/Analyses/Basecall_1D_000/BaseCalled_template/Fastq` dataset. I have also tested Nanopolish 0.8.0 and I had the same error. Could you please help me to solve?

Thanks,
Maria Angela

**Comment by rrwick** [comment]
Hi Maria,

If you're trying to use Nanopolish to polish a genome, and you already have a fastq of the reads, then you shouldn't need the `nanopolish extract` command. Just use `nanopolish index` followed by `nanopolish variants` as described [here](https://github.com/jts/nanopolish#computing-a-new-consensus-sequence-for-a-draft-assembly).

If you don't have a fastq of the reads (i.e. you only have the fast5 files), then a number of tools exist to pull the sequences out. [Poretools](https://poretools.readthedocs.io/en/latest/) is one option. I also wrote [my own script](https://github.com/rrwick/Fast5-to-Fastq) for this a while ago (though it's deprecated now). There are others as well.

I hope that helps! I'm going to close this issue now, but if you're still having problems with Nanopolish, I'd suggest making an issue on the [Nanopolish issues page](https://github.com/jts/nanopolish/issues). You'll probably get better advice there!

Ryan

**Comment by ma-diroma** [comment]
Thanks for your help.

Best wishes,
Maria Angela
